# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tripper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tripper
  pod 'ScalingHeaderScrollView'
  pod 'ProgressIndicatorView'
  pod 'ExytePopupView'
  
  target 'tripperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tripperUITests' do
    # Pods for testing
  end

end
